# Generated by Django 3.0.6 on 2020-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(blank=True, max_length=255, null=True)),
                ('code_col', models.CharField(blank=True, max_length=255, null=True)),
                ('code_code', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_code',
            },
        ),
        migrations.CreateModel(
            name='TblCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('sub_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('view_cnt', models.CharField(max_length=255)),
                ('like_cnt', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_community',
            },
        ),
        migrations.CreateModel(
            name='TblCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('kanji', models.CharField(max_length=255)),
                ('hiragana', models.CharField(max_length=255)),
                ('katakana', models.CharField(max_length=255)),
                ('hangul', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_core',
            },
        ),
        migrations.CreateModel(
            name='TblCoreEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_id', models.IntegerField()),
                ('ex_kanji', models.CharField(max_length=255)),
                ('ex_hangul', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_core_ex',
            },
        ),
        migrations.CreateModel(
            name='TblFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('enc_name', models.CharField(max_length=255)),
                ('ext', models.CharField(max_length=255)),
                ('raw_size', models.IntegerField()),
                ('enc_size', models.CharField(max_length=255)),
                ('save_path', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_file',
            },
        ),
        migrations.CreateModel(
            name='TblIndexJlpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_index_jlpt',
            },
        ),
        migrations.CreateModel(
            name='TblNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title_id', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('read_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('regist_id', models.IntegerField(blank=True, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='TblPointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quiz_id', models.IntegerField()),
                ('point', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_point_history',
            },
        ),
        migrations.CreateModel(
            name='TblProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('difficult', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_problem',
            },
        ),
        migrations.CreateModel(
            name='TblProblemCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('core_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_problem_core',
            },
        ),
        migrations.CreateModel(
            name='TblProblemLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_problem_like',
            },
        ),
        migrations.CreateModel(
            name='TblProblemQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('quiz_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_problem_quiz',
            },
        ),
        migrations.CreateModel(
            name='TblQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('quiz', models.CharField(max_length=255)),
                ('quiz_hangule', models.CharField(max_length=255)),
                ('problem1', models.CharField(max_length=255)),
                ('problem2', models.CharField(max_length=255)),
                ('problem3', models.CharField(max_length=255)),
                ('problem4', models.CharField(max_length=255)),
                ('solve', models.CharField(max_length=255)),
                ('solution', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_quiz',
            },
        ),
        migrations.CreateModel(
            name='TblReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reply',
            },
        ),
        migrations.CreateModel(
            name='TblReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_report',
            },
        ),
        migrations.CreateModel(
            name='TblReReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_id', models.IntegerField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_re_reply',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('jlpt', models.IntegerField(blank=True, null=True)),
                ('profile_img', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=255, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('regist_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('modify_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_date', models.DateTimeField(blank=True, null=True)),
                ('reset_ip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='TblUserJlpt',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_jlpt_n1', models.IntegerField(blank=True, null=True)),
                ('pub_jlpt_n2', models.IntegerField(blank=True, null=True)),
                ('pub_jlpt_n3', models.IntegerField(blank=True, null=True)),
                ('pub_jlpt_n4', models.IntegerField(blank=True, null=True)),
                ('pub_jlpt_n5', models.IntegerField(blank=True, null=True)),
                ('n1_update_date', models.DateTimeField(blank=True, null=True)),
                ('n2_update_date', models.DateTimeField(blank=True, null=True)),
                ('n3_update_date', models.DateTimeField(blank=True, null=True)),
                ('n4_update_date', models.DateTimeField(blank=True, null=True)),
                ('n5_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_jlpt',
            },
        ),
    ]
