# Generated by Django 3.0.6 on 2020-06-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user_profile',
        ),
    ]
