# Generated by Django 3.0.6 on 2020-06-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_auto_20200601_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('enc_name', models.CharField(max_length=255)),
                ('ext', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('save_path', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_img', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_manage',
            },
        ),
    ]
