# Generated by Django 3.0.6 on 2020-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200607_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizunit',
            old_name='problem1',
            new_name='right_answer',
        ),
        migrations.RenameField(
            model_name='quizunit',
            old_name='problem2',
            new_name='wrong_answer1',
        ),
        migrations.RenameField(
            model_name='quizunit',
            old_name='problem3',
            new_name='wrong_answer2',
        ),
        migrations.RenameField(
            model_name='quizunit',
            old_name='problem4',
            new_name='wrong_answer3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_group',
        ),
        migrations.RemoveField(
            model_name='quizunit',
            name='solve',
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('', 'ALL'), ('N1', 'JLPT N1'), ('N2', 'JLPT N2'), ('N3', 'JLPT N3'), ('N4', 'JLPT N4'), ('N5', 'JLPT N5'), ('ETC', 'ETC')], default='ETC', max_length=6),
        ),
        migrations.AlterField(
            model_name='quizgroup',
            name='level',
            field=models.CharField(choices=[('', 'ALL'), ('N1', 'JLPT N1'), ('N2', 'JLPT N2'), ('N3', 'JLPT N3'), ('N4', 'JLPT N4'), ('N5', 'JLPT N5'), ('ETC', 'ETC')], default='ETC', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jlpt',
            field=models.CharField(choices=[('N0', 'no license'), ('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1')], default='N0', max_length=6),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('', 'ALL'), ('N1', 'JLPT N1'), ('N2', 'JLPT N2'), ('N3', 'JLPT N3'), ('N4', 'JLPT N4'), ('N5', 'JLPT N5'), ('ETC', 'ETC')], default='ETC', max_length=6),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('', 'ALL'), ('N', 'Naming word'), ('V', 'Verb'), ('ADJI', 'adjective I'), ('ADJN', 'adjective N'), ('ADV', 'adverb'), ('ETC', 'ETC')], default='ETC', max_length=6),
        ),
    ]
